# Nginx 配置文件用于 Electron 应用自动更新服务器

server {
    listen 8080;
    server_name localhost;
    root /tmp/electron-update-server/latest/
    index index.html;

    # 设置跨域访问
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Headers "X-Requested-With";
    add_header Access-Control-Allow-Methods "PUT,POST,GET,DELETE,OPTIONS";
    add_header X-Powered-By "nginx";

    # 处理预检请求
    if ($request_method = 'OPTIONS') {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Headers "X-Requested-With, Content-Type";
        add_header Access-Control-Allow-Methods "PUT,POST,GET,DELETE,OPTIONS";
        add_header Content-Type "text/plain charset=UTF-8";
        add_header Content-Length 0;
        return 204;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    # 返回正确的 MIME 类型
    location ~* \.(yml|yaml)$ {
        add_header Content-Type 'text/yaml; charset=utf-8';
    }

    location ~* \.(json)$ {
        add_header Content-Type 'application/json; charset=utf-8';
    }
}
